### PR TITLE
Pass clibraries paths to libdl via LD_LIBRARY_PATH, SHLIB_PATH

### LINKED ISSUE #121: clibraries limited to compile search path. Not used at runtime
From https://github.com/andreas-kupries/critcl/issues/116#issuecomment-1037809980

> [esternin] figured out what is not working with the libraries outside of the default LD_LIBRARY_PATH. The crit::clibraries does get used when compiling the code, but not when running it. The loader does not get passed this via, for example, the setting of LD_LIBRARY_PATH at run-time. I think this is a bug. The workaround is to only use libraries that are in default locations, like /usr/local/lib. This probably is a separate issue, I'll let you decide.

From later in the thread

> [aku] forgot to respond to

> >  [esternin] think the issue is the inconsistency, because C is a compiled language, and tcl is interpreted, I am expecting that if the code did not raise a flag at compile time - it found the routines specified in crit::clibraries - then the code should run as well.

> earlier. ... This was actually a good argument for me to see it as a bug to be fixed. Less about the C/Tcl difference, and more that while I use critcl pretty much exclusively in package mode (i.e. ahead of time compilation via critcl -pkg ...) it does have a compile and run mode where you simply package require the critcl-based package and it compiles and loads the C code for you on the fly (if you have a working cc, with caching under ~/.critcl/<platform>). Without a fix this mode breaks on non-standard library locations.

To fix.

### PR DESCRIPTION
**Pull request by andreas-kupries**
fix #121 

Pass clibrary paths to loader for extended search
Both for compile and run, and generated package (via index).

Deeper testing to be done tomorrow. Right now only willing to admit that the paths indeed appear in what I believe to be the correct places. Needs however proper testing with actual non-standard path and a shlib there.

### CODE REVIEW

**Comment by andreas-kupries** [comment]
And not working out. The idea was to extend env(LD_LIBRARY_PATH) of the running tclsh.
This does not have any effect.
I can confirm that the desired path is added, and yet the library is not found.
OTOH, setting LD_... before starting tclsh I see the path doubled (expected), and the library now is found.
I suspect that the dynamic loader, i.e. libdl, looks at LD_... once, at startup, and then never again.

Ok, the other idea I had works:

>  lappend cmdline -Wl,-rpath,$path

I.e. put the search path for the dependency into the package shlib during linking.

My problem with this solution is portability. Will this work for Solaris, HPUX, AIX compilers ? How about Windows?

Even with these questions, it looks to be better than before, it should work for anything using gcc.

**Comment by andreas-kupries** [comment]
Keeping `-Wl,-rpath,DIR`, and made it configurable, for the targets which use something different.

This should work.

@esternin Please test if this PR/branch obviates the need for your workaround.

**Comment by esternin** [comment]
Sounds like a good solution to me... Sorry to have gone silent I am away for a few days. Will test asap.

**Comment by esternin** [comment]
Hmm... did not seem to make a difference, at least not on RHEL 7 (our production nodes) - unless I did something wrong:
```
$ git fetch https://github.com/andreas-kupries/critcl 121-clibraries-runtime
...
From https://github.com/andreas-kupries/critcl
 * branch            121-clibraries-runtime -> FETCH_HEAD
$ git checkout FETCH_HEAD
Checking out files: 100% (102/102), done.
Note: checking out 'FETCH_HEAD'.
...
$ su
# tclsh build.tcl install --lib-dir /usr/share/tcltk
...
# ldconfig
# exit
$ ./aspect 
Error in startup script: couldn't load file "/home/esternin/.critcl/linux-glibc2.17-x86_64/v3118_c5f270b33c73cdd4a1626efe2b09c00b.so": libASICamera2.so: cannot open shared object file: No such file or directory
    while executing
"::load $shlib $init"
    (procedure "Load" line 10)
    invoked from within
"Load $file"
    (procedure "cbuild" line 88)
    invoked from within
"cbuild [This]"
    (procedure "critcl::load" line 4)
    invoked from within
"critcl::load"
    (file "./aspect" line 173)
```

**Comment by andreas-kupries** [comment]
I suspect that you forgot to remove the old shared library from the cache directory.
You likely did not change the sources of the package in question, thus the library was not regenerated and the old, cached libary used. Which does not have the `-rpath` set.

Easiest way to force a rebuild would be to delete the cache, i.e. `/home/esternin/.critcl/*`.

**Comment by esternin** [comment]
No, I did not forget.  Here it is again:
```
$ head -n 3 aspect
#!/bin/bash
# the next line restarts using wish\
exec wish "$0" "$@"

$ rm -rf ~/.critcl

$ ./aspect 
Error in startup script: couldn't load file "/home/esternin/.critcl/linux-glibc2.17-x86_64/v3118_c5f270b33c73cdd4a1626efe2b09c00b.so": libASICamera2.so: cannot open shared object file: No such file or directory
    while executing
"::load $shlib $init"
    (procedure "Load" line 10)
    invoked from within
"Load $file"
    (procedure "cbuild" line 88)
    invoked from within
"cbuild [This]"
    (procedure "critcl::load" line 4)
    invoked from within
"critcl::load"
    (file "./aspect" line 174)
```

**Comment by andreas-kupries** [comment]
Ok. So it is not the easy possible issue. ... What is the output of

> ldd /home/esternin/.critcl/linux-glibc2.17-x86_64/v3118_c5f270b33c73cdd4a1626efe2b09c00b.so

and 

> readelf -d /home/esternin/.critcl/linux-glibc2.17-x86_64/v3118_c5f270b33c73cdd4a1626efe2b09c00b.so | grep -i path

?

Given your problems it should confirm that the shlib does not have the path for `libASICamera2.so` added.

Ah, how did you specify the path for `libASICamera2.so` ? Via -L ? Or as full path like `/path/to/libASICamera2.so` ?
I do not recognize the second form ... And now that I am reminded of that I will see to add that recognition.

I will add some debugging/messaging to the branch to better see what is done (clibraries arguments, run path insertion).

**Comment by andreas-kupries** [comment]
Pushed changes:
  - Process arguments like `/path/to/shlib.so` of `clibraries` for search paths (here `path/to`).
  - Preventing rpath handling on Windows (-rpath equivalent is not known. Do you know ?)
  - Added `msg` calls to show the collected information, and what search paths are added to the shlib, if any.

Note 1: `msg` calls are active only when used with the `critcl` app. I.e. run `critcl -keep -pkg your-package.tcl` to see the output.
If necessary add a `package provide your-dummy-package 0` to the code, i.e. if it is not a proper package.
(Side note: They are inactive for `compile & run` to not litter the application output with compilation output as an app starts).

Note 2: `critcl` results and compile/run cache are in separate directories. 

Note 3: The `app-critcl/critcl.tcl` file contains the definition of `critcl::msg` used by the app, around line 100. Copying this into the package code, after `package require critcl` will activate the `msg` calls for compile/run as well. If using the app is really out of the question.

To come: I have to check if Mac OSX (clang cc) supports `-Wl,-rpath,DIR` ... At first look it should support `-rpath` as is.
It also comes with `--library-directory <arg>`, `--library-directory=<arg>` as their own variants of `-L<arg>`. Planning to support that too.

**Comment by esternin** [comment]
I am on the road, so will reply to what I can.
```
critcl::cheaders -I/opt/ASI_linux_mac_SDK_V1.21/include
critcl::clibraries -L/opt/ASI_linux_mac_SDK_V1.21/lib/x64
critcl::clibraries -lASICamera2
```
is how I tell where the library is, you did point out that the effect is cumulative.

```
$ ldd /home/esternin/.critcl/linux-glibc2.17-x86_64/v3118_c5f270b33c73cdd4a1626efe2b09c00b.so
...
libASICamera2.so => not found
....
```
and now my flight is boarding...

**Comment by andreas-kupries** [comment]
Safe travels.

And with the recent pushes we should be able to determine where things go astray.

**Comment by esternin** [comment]
```
readelf -d /home/esternin/.critcl/linux-glibc2.17-x86_64/v3118_c5f270b33c73cdd4a1626efe2b09c00b.so | grep -i path
```
returns nothing.

**Comment by andreas-kupries** [comment]
What happens when testing as per https://github.com/andreas-kupries/critcl/pull/122#issuecomment-1047028041, using commit  5160185576b131d8d9e99a3cdfa27f3cb616e238 ?

**Comment by esternin** [comment]
I do not seem to have `app-critcl/critcl.tcl`, the only `critcl.tcl` I see around line 100 has nothing about `::msg`

This does not seem to do anything
```
$ critcl -keep -pkg aspect.tcl
Config:   linux-x86_64-gcc
Build:    linux-x86_64-gcc
Target:   linux-x86_64
Source:   aspect.tcl aspect.tcl invoked with too many arguments (3), abort.
```

So I do not think I understand the notes in https://github.com/andreas-kupries/critcl/pull/122#issuecomment-1047028041

**Comment by andreas-kupries** [comment]
I guess I went to deep again ... I tried to explain why it is better to use the `critcl` app for further debugging instead of what you did before, namely calling your own app and having critcl work in the background. (No messages, and heavy editing needed to get messages out of it).

Going back to your attempt at using the app ...
There should have been more output, and no error, I believe.
Please allow me to reset to basics ...

I assume that your checkout is on branch `121-clibraries-runtime`.
  * Verified via `git branch -a|grep '\*'`

I assume that you have commit a153c4d4c6f092c6f80d6915e2e8a4648fec2ef4 or later (5160185576b131d8d9e99a3cdfa27f3cb616e238)  checked out
  * Verified via `git log | head -5`

I further assume that you ran `./build.tcl install` from that checkout.
May I see the log generated during installation ?
(Best attached here, instead of inlined)
I am actually only interested in the part starting from

> Installed C package:	critcl::md5c

This is where critcl installs its own C packages. This should already show the extended output.

**Comment by andreas-kupries** [comment]
One idea: `aspect.tcl invoked with too many arguments (3), abort.`

Your file is an application, it looks at `argv`. And the critcl app is not clearing `argv`, so it sees `-keep -pkg aspect.tcl` and chokes on it. For the purpose of debugging the library handling I believe that you should disable the argument processing of your app.

Better maybe, place the pure critcl part of your code into a separate file which does not have any kind of application code.

**Comment by andreas-kupries** [comment]
Might have been better to ask for the entire log.

> $ sudo tclsh build.tcl install --lib-dir /usr/share/tcltk
...
Installed package:      /usr/share/tcltk/critcl_md5c0.12

The line you started from above, is not the line I asked to start from
> Installed C package: critcl::md5c

If there was the output I looked for, then it was in the `...` section.

Next, much better.

> Source:   critcl_test.tcl  (provide  )	cheaders __+=__ -I/opt/ASI_linux_mac_SDK_V1.21/include
	clibraries __+=__ -L/opt/ASI_linux_mac_SDK_V1.21/lib/x64
	clibraries __+=__ -lASICamera2
>
> Library:  critcl_test.so
	cobjects __+=__ /home/esternin/.critcl/pkg25149.1646069713/v31182_00000000000000000000000000000018_pic.o
	clibraries __+=__ -L/opt/ASI_linux_mac_SDK_V1.21/lib/x64 -lASICamera2
 (tclStubsPtr     =>  TclStubs *tclStubsPtr;)
 (tclPlatStubsPtr =>  TclPlatStubs *tclPlatStubsPtr;)
	__rpath +=__ /opt/ASI_linux_mac_SDK_V1.21/lib/x64

__Now this looks good__.
All the output I expected is present.
All the lines matching `+=`.
We especially see the `rpath +=` derived from your `-L...` option. This happens at the top line of 
https://github.com/andreas-kupries/critcl/blob/121-clibraries-runtime/lib/critcl/critcl.tcl#L4605-L4614
just before the linker is called with the constructed cmdline.

The error and stack trace indicate that the `critcl_test.tcl` file is missing a `package provide` command to make it a proper package. Looking into the uploaded critcl_test.tcl file (Thank you) confirms that.

I mentioned the need for that before, did I ?
Regardless, new commit pushed to abort early when `package provide` is missing, with a nicer message, and without a stacktrace.

Please fix your `critcl_test.tcl` file and try again.

**Comment by esternin** [comment]
> I mentioned the need for that before, did I ?

You did, and I had it in for a while, but since it did not work, I deleted it and forgot to add it back for this test, my apologies.  With that, the compiled package seems fine:
```
$ critcl -keep -pkg critcl_test.tcl 
Config:   linux-x86_64-gcc
Build:    linux-x86_64-gcc
Target:   linux-x86_64
Source:   critcl_test.tcl  (provide critcl_test 0)	cheaders += -I/opt/ASI_linux_mac_SDK_V1.21/include
	clibraries += -L/opt/ASI_linux_mac_SDK_V1.21/lib/x64
	clibraries += -lASICamera2

Library:  critcl_test.so
	cobjects += /home/esternin/.critcl/pkg11165.1646082685/v31182_00000000000000000000000000000018_pic.o
	clibraries += -L/opt/ASI_linux_mac_SDK_V1.21/lib/x64 -lASICamera2
 (tclStubsPtr     =>  TclStubs *tclStubsPtr;)
 (tclPlatStubsPtr =>  TclPlatStubs *tclPlatStubsPtr;)
	rpath += /opt/ASI_linux_mac_SDK_V1.21/lib/x64
Package:  lib/critcl_test
Files left in /home/esternin/.critcl/pkg11165.1646082685
$ ldd  /home/esternin/.critcl/pkg11165.1646082685/v31182_00000000000000000000000000000024.so
...
	libASICamera2.so => /opt/ASI_linux_mac_SDK_V1.21/lib/x64/libASICamera2.so (0x00007fa6c810f000)
...
```
So everything seems fine in the compiled package mode (but I cannot `package require /home/esternin/.critcl/pkg11165.1646082685` in my tcl code, I still need to complete making it into a package and install it into `/usr/share/tcltk` first?).  

This is actually the very first time I have compiled a tcl script, as I always work in the interpreted code mode.  How can this interpreted mode be made operational?

**Comment by esternin** [comment]
I guess, returning to my own previous answer to this question, making use of `LD_LIBRARY_PATH` to point to an off-path library at runtime, the first lines of my file are now:
```
#!/bin/bash
# the next line restarts using wish\
LD_LIBRARY_PATH="/opt/ASI_linux_mac_SDK_V1.21/lib/x64:$LD_LIBRARY_PATH" exec wish "$0" "$@"

```
and with the latest changes now in play this works.  So I think you have fixed this, and #122 can be pulled in.

Thanks!

**Comment by andreas-kupries** [comment]
> You did, and I had it in for a while, but since it did not work, I deleted it and forgot to add it back for this test, my apologies.

no problem

> With that, the compiled package seems fine:

good. Note, the line

> Package:  lib/critcl_test

tells you that the generated package was placed into the named sub directory of your working directory. That is a full-blown package with pkgIndex.tcl, the generated shlib, and supporting tcl code.

> I still need to complete making it into a package 

That is what compile mode did for you. See my note above where it left the result.

>  How can this interpreted mode be made operational?

Given that it uses the same code internally as the ahead-of-time it actually should work, now, with the checkout you have installed, and without the LD_LIBRARY_PATH workaround. And if not then I have to consider some kind of mismatch, i.e. that running the `aspect.tcl` uses a different critcl package than we are thinking it does.

Adding the Tcl command `puts [package ifneeded critcl [package present critcl]]` after the block running `package require critcl` in aspect.tcl will tell us where that critcl comes from.

**Comment by esternin** [comment]
Good call!  I did, indeed have a remnant of critcl.3.1.8 that was being loaded.

I had to re-install into `/usr/share/tcl8.5` on RedHat; on Ubuntu it would have been `/usr/share/tcltk` for packages to be found.

Now, compile-on-the-fly works!

**Comment by andreas-kupries** [comment]
Glad to hear that. I will disable the extended debug output tomorrow, think about the messaging for the result location in ahead-of-time mode, and then merge the PR.

Here it is time to sleep.

**Pull request merged**
